name: aidtep
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - expat=2.6.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.0
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - filelock==3.15.4
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.0.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - scikit-learn==1.5.1
      - scipy-1.13.1
      - sympy==1.13.0
      - threadpoolctl==3.5.0
      - torch==2.3.1
      - typing-extensions==4.12.2
      - loguru==0.7.2
      - pathlib==1.0.1
      - pyyaml==6.0.1
      - pandas==2.2.2
      - matplotlib==3.9.1
      - h5py==3.11.0


